### ISSUE TITLE
Comments on revision

### ISSUE THREAD

**Issue by dicook** [natydasilva/PPforestViz#1]
- [x] I revised the response, Discussion 
- [x] Would you put in a section, before the bibliography which lists the code and data sources, particularly the source of the app code. I'm not sure that I have access to the code for the app?
- [x] Do you think you could change the crab category names to be just O and B, instead of orange and blue? This would address the reviewers concern about color palette and categories. And also just use F anf M for the sex.
- [x] I think it is better to use OOB than job. Can you make that change?

**Comment by natydasilva** [comment]
I have included a Supplementary material section with the link to paper repo and shiny app repo to reproduce results.
I have changed category names and include OOB instead of oof
